version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql-database
    volumes:
      - "./docker/mysql:/data/"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'data-demo'
